### ISSUE TITLE
Bluebird is no longer in use in Knex

### ISSUE THREAD

**Issue by FPierre** [alekbarszczewski/knex-hooks#11]
Since `knex@0.20.11`, Bluebird is no longer in use

So it produce the following error: `Cannot find module 'bluebird' from 'node_modules/knex-hooks/src/run-hooks.js'` with:
* knex@0.21.1
* knex-hooks@0.0.8

**Comment by hiddentao** [comment]
Just saw this too. Fix: https://github.com/alekbarszczewski/knex-hooks/pull/12
